SELECT
    A.USER_ID,
    A.NICKNAME,
    TOTAL_SALES
FROM USED_GOODS_USER A
JOIN 
(SELECT 
    WRITER_ID, 
    STATUS, 
    SUM(DECODE(STATUS,'DONE',PRICE,0)) AS TOTAL_SALES 
 FROM USED_GOODS_BOARD WHERE STATUS='DONE'
 GROUP BY WRITER_ID, STATUS
) B 
ON A.USER_ID = B.WRITER_ID
WHERE TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC
