SELECT
    TO_NUMBER(HOUR) AS HOUR,
    COUNT
FROM
    (
    SELECT
        TO_CHAR(DATETIME,'HH24') AS HOUR,
        COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY TO_CHAR(DATETIME,'HH24')
    )
WHERE HOUR <= 19 AND HOUR >= 9
ORDER BY HOUR
